### ISSUE TITLE
Breadcrumb is not wrapped when it is too long

### ISSUE THREAD

**Issue by stevedxu** [saschaleib/dokuwiki-template-ad-hominem#11]
When Breadcrumb is too long, it is not wrapped. It caused the page layout to shift and damaged the whole look and feel.

**Comment by saschaleib** [comment]
Hello and thanks for the info. Could you post some more information on when and how this happens? I could not reproduce it with Firefox, Chrome or Edge...

The expected behaviour would be to hide the overflow to the right, as in this screenshot:
![image](https://user-images.githubusercontent.com/961863/148250761-8b85aa2e-9a10-41ba-be00-3bccfdcb7e37.png)

An improvement that I am considering is to hide the "middle" elements in a breadcrumb if this happens, so that the last entry remains visible, but that would require some JS, while I much prefer solutions that can be done in plain CSS.

**Comment by stevedxu** [comment]
That's because your page name is short and your level is also limited. Try
to give a super long page name and with multiple levels hierarchy and you
will see it.

Thanks,
*Steve Xu*

**Comment by saschaleib** [comment]
Hm, looks like this for me: 
![image](https://user-images.githubusercontent.com/961863/148256027-f0458524-4b71-4706-9480-204848cbc95e.png)

**Comment by stevedxu** [comment]
Yeah so now if you add one more level under the extreme long page name, you
will see what I mean.

Thanks,
*Steve Xu*

**Comment by saschaleib** [comment]
Hm, I reckon the best solution here would be to limit the length of headlines in the crumbtrail path, like so: 
![image](https://user-images.githubusercontent.com/961863/148262888-681529f8-685b-40de-96f9-91b7b5c0e4c3.png)

**Comment by stevedxu** [comment]
I think that works perfectly fine if you can implement that

**Comment by saschaleib** [comment]
I think that's indeed an improvement to the previous style. I have already pushed the change to the repo, will be added to the next release (I'll probably publish tonight or tomorow).

**Comment by stevedxu** [comment]
Wonderful. Just a reminder. When you implement those, please also take care of print layout and make sure it will do the same. Thanks a lot.

**Comment by saschaleib** [comment]
That should be easy, as the breadcrumbs are not visible in print view ;-)

**Comment by saschaleib** [comment]
Version 0.5.3, which was published today (05.01.2022) fixes this and adds some more improvements to the breadcrumbs.
