### ISSUE TITLE
Update flag always set?

### ISSUE THREAD

**Issue by Dob4115** [saschaleib/dokuwiki-template-ad-hominem#15]
Have you noticed that the page to update the template always shows there is a new version of the template? I just updated (2022-01-06) and I still see that an update is available. It does not show the "url has changed" notice like it did before I updated.

**Comment by saschaleib** [comment]
Yes, that seems to be a problem of the update manager. I assue it also has to do with the way I release the beta versions (as "releases", rather than publishing the main branch). However, as long as the template is still in "beta", this is the preferred way, as this gives more control over when a new release is available. The alternative would entail a risk of installing half-ready features to the users, so I rather live with the message...

**Comment by Dob4115** [comment]
ok, as long as it's known

**Comment by saschaleib** [comment]
This issue should be gone now that there is finally an official "release" version. In fact, getting rid of these messages was my main objective in officially releasing "1.0" :-)

Could you check? If this is good for you I would close this issue.

**Comment by Dob4115** [comment]
Yes, looks good!

**Comment by saschaleib** [comment]
Fixed with 1.0
