### ISSUE TITLE
Manual switching for dark/light mode

### ISSUE THREAD

**Issue by evs38** [saschaleib/dokuwiki-template-ad-hominem#16]
Is it possible to add the manual switch to enable and disable the dark mode?

**Comment by saschaleib** [comment]
Hello there, the dark mode is meant to correspond to the visitor's preference, not the site owner's. That is why there is no such option. 

However, in cases where the site can not comply with the dark mode (e.g. because there are specific images or similar things) the template has an option to _disable_ the client-side dark mode.

In situations where you would prefer to have a dark mode, regardless of the user preferences, you *could* in principle edit the template colours using the "Template Style Settings", but I would not recommend this. It is usually better to allow the user to chose their preference here.

**Comment by evs38** [comment]
Yes, I know that that is the visitor preference. So there is no way to force enable dark mode?

**Comment by saschaleib** [comment]
As I said: you can override the default colours.
