### ISSUE TITLE
Code block: long line runs beyond panel

### ISSUE THREAD

**Issue by suedunham** [saschaleib/dokuwiki-template-ad-hominem#21]
When using `<code>` or `<file>` tags to enclose a block of code, a long line remains unbroken or unwrapped and simply extends through the main page panel and makes the right edge wider.

For comparison's sake, the default DokuWiki template adds a horizontal scrollbar to the code `pre` element, and the Bootstrap3 template forces the line to wrap within it. Either approach would be preferable.

For an example, I've just pasted the code from `doku.php` into a `<code>…</code>` block. Line 107 shows what I mean.

I'm using the current Igor version of DokuWiki on a Windows machine in Chrome.

**Comment by saschaleib** [comment]
Thanks, looks like I will need to do a couple of CSS revisions when I am back home :-)

**Comment by saschaleib** [comment]
Hello again, so I checked the specs and it turns out `<code>` is an inline element, so allowing an overflow to be scrollable doesn't make sense here (and also isn't the case in the original DokuWiki template), but `<pre>`, which is how DokuWiki renders the "`<file>`" tag, is block-level and indeed should get horizontal scrolling in these cases.
This is now in the repository and will be rolled out with the next update. If you are impatient, you can manually update the CSS file "content.less.

**Comment by saschaleib** [comment]
This is now fixed in version 1.4, released today.
