### ISSUE TITLE
Admin page plugins list looks out of place

### ISSUE THREAD

**Issue by suedunham** [saschaleib/dokuwiki-template-ad-hominem#23]
I've loaded in my typical plugins, and the Admin page seems to place them weirdly. I'd expect the whole list to be together underneath the main block of items.

![ad_hominem_admin](https://user-images.githubusercontent.com/42522840/211047492-35d050db-e7fa-4352-a869-0c2719de0ce2.jpg)

I have a question too about plugins in general. Are you handling the ways they may not interact well with the template as those become known, or would that be more the plugin developer's or wiki users's task? Maybe some time after other priorities are done? Would that depend on the nature of the problem?

I've already had to touch up the css for one of them in the dark themes of the Bootstrap3 template, for instance. A different issue with another plugin may go deeper than that.

**Comment by saschaleib** [comment]
Hello again, indeed, the Admin page uses a two-column layout on desktop screen-sizes. This is intended, as it makes better use of the screen space and reduces the need to scroll to the item needed (the one I need the most usually ends up as the very last one in the list, so I have strong feelings about keeping it reachable without a need to scroll :-)

As for other plugins, there is unfortunately a wide range of quality differences between them, and not every plugin author is following the best practices in how to refer to pre-defined colours, etc. This is also why I have re-implemented the "Cookie banner" plugin into the template, as this is vitally important for my sites, but would have looked very much out of place without the proper formatting.

Of course, the "user-controlled dark mode" in this template makes things even more difficult, as most plugins do not support the mechanism behind that, and there is a good chance that some things may still look weird.

However, there is no way to ever provide workarounds for all the plugins out there in the template, so there is always a chance that you need to add some custom-CSS in order to fully integrate some specific plugin to your site. If you have a specific issue, I can try to help. However, unless it is directly related to a bug in the template, I would prefer to discuss these in the [DokuWiki User Forum](https://forum.dokuwiki.org/), where also other users can participate, and where others can also more easily find the solutions we discuss, in case they have the same problems.
