### ISSUE TITLE
Section highlight border

### ISSUE THREAD

**Issue by suedunham** [saschaleib/dokuwiki-template-ad-hominem#27]
I don't know if this is a bug, but it's not what I imagined. The color of the `.section_highlight` class border is set to `orange` where I had guessed it may be tied in with the `__focus_color__` setting.

**Comment by saschaleib** [comment]
Indeed, I gave the `section_highlight` class a hard-coded colour at the time, because I did not consider it a "focus" in the same sense as the search field can receive the focus. However, I agree that this might still be the better choice here, as it gives the user the opportunity to avoid it conflicting with any custom background or other colour... so, yes, this is definitely an improvement.

A little funfact: the standard template also has a section-highlight, but it is so minimalistic that most users never actually notice it ;-) I definitely wanted a style here that screams at the user: HERE, THIS IS THE SECTION YOU ARE GOING TO EDIT :-D
