### ISSUE TITLE
Page Action Button Locations

### ISSUE THREAD

**Issue by Dob4115** [saschaleib/dokuwiki-template-ad-hominem#4]
Is there any way to force the page action buttons to be in view as you scroll the page? It's annoying to be reading a page, then have to scroll all the way to the bottom to edit, rename, etc.

**Comment by saschaleib** [comment]
Hm, the way I am using DokuWiki, the "edit" link is only used when I am creating a new page, or if the page is very short, i.e. has no headlines. In fact, I put a lot of effort into the new edit icons for each section, because these are much more important for me...

But of course, my use-case is not necessarily good for everybody. Could you give me some more information about how you use the page - maybe even some link to an existing page that would be typical for you? Maybe I can figure something out...

**Comment by Dob4115** [comment]
Interesting... I guess I am usually moving things around the page so editing a single section is not something I do a lot. This is actually one aspect of the default template I kind of like... those floating icons on the right side. Understood if you want them removed, but that served my purposes well.

While the new edit icons aren't bad, I do feel like they are a little big. Understand wanting to move away from the garish buttons, but reducing the circle radius might help? (in my opinion, of course... you do what you want!)

**Comment by saschaleib** [comment]
I'm afraid the icons would rather break with the visual consistency of the template. So no can do here. But one hint: if you want a quicker access to the page editor, I would consider adding a bookmarklet for doing just this...
