### ISSUE TITLE
Is there a way to make a strikethrough more pronounced in the black theme?

### ISSUE THREAD

**Issue by eightysixed** [saschaleib/dokuwiki-template-ad-hominem#46]
This isn't necessarily an issue, but more of an improvement. 
Is there a way to make the strikethrough using `<del>asdf1234</del>`  more pronounced through a few CSS tweaks?
I've attached a screenshot of what I'm talking about. It's fine on strikethrough's with links, but the red strikethrough on the black background is barely noticeable. It's even more unnoticeable on mobile.

Again, this is just a question/improvement request, no biggie if it's a no-go :) 
![C5AAEEED-B692-49A5-8330-010EFF940758_4_5005_c](https://github.com/saschaleib/dokuwiki-template-ad-hominem/assets/1641513/1d804306-de2d-4eb8-bcbf-f5d3934add63)

**Comment by saschaleib** [comment]
Hello @eightysixed, that is actually an interestiing issue, as I was tinkering with the strikethrough style for quite a while and in all honesty I am still not entirely happy with the result...

My main problem here is that the `<del>` tag, which is used by DokuWiki as the default for strikethroughs is actually most _of the time_ not used properly. The W3C Specs ([link](https://html.spec.whatwg.org/multipage/edits.html#the-del-element)) actually state this about this element:

> The `del` element represents a removal from the document.

The intended use for this element is e.g. in a diff view (e.g. compare versions) and thus the best way to format this would rather be red text with a strikethrough, so the removal is very clear.

However, that is not how most users (myself included) will probably use it. I reckon most users will assign a strikethrough to indicate an invalid or inaccurate. 

However, for this purpose there is actually the `<s>` element, which is specified ([link](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-s-element)) as follows:

> The `s` element represents contents that are no longer accurate or no longer relevant.

However, this element is not available without plugins, so people will likely not use it...

Another aspect to look at here is that the regular strikethrough style is often extremely difficult to read - especially when it is used for short expressions, like single numbers or even symbols... it often works better for whole words.

Between all of these, I have to find a compromise that works in all situations, and I found that the semi-transparent red strikethrough keeps legibility high, can be recognized as "deleted", if needed, but also as "invalid" when the formatting is used in this meaning.

So could this be improved? Sure, there is a lot of fine-tuning possible. However, if your own use-case is very specific and known, it might be easier if you override the strikethrough style in the `user.css` file rather than in the template itself.

So, was this just a very elaborate way of telling you to do it yourself :-) well, no, I'll still keep the issue open, just to remind me to look at the strikethrough when I'm back from holidays ;-) but I don't consider this a high-priority change, and in any case, the most likely outcome is that the strikethrough may just be a tiny bit less transparent or so.

**Comment by eightysixed** [comment]
Hey there!
I just wanted to send a friendly reminder on this :)
Also, if I upgrade to Kaos that was just released yesterday, will the template break?
If you have to change some stuff, try to play with the strikethrough at the same if you have time :)

**Comment by saschaleib** [comment]
I'm afraid the only real improvement here would be to change the way the DW core handles strikethrough tags (should be `<s>` instead of `<del>`).

As long as these are mixed up, the semi-transparent strikethrough is probably the best. If you need a more visible style, you can override the [text-decoration-color](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-color) in the userstyle.css.

**Comment by eightysixed** [comment]
Okay, I'll go the manual override method.
But before I do, do you think if I upgrade to Kaos it'll break Ad-Hominem?
There's 2 features I'm interested in.

**Comment by saschaleib** [comment]
I only had a quick view on Kaos yet, but I could install Ad Hominem without problems, and at least there are no obvious problems...

I'll still do some more tests to make sure there are no hidden issues, but it looks pretty safe to update :-)
