### ISSUE TITLE
List looks weird when items contain linked files like PDFs (Version 1.6.4)

### ISSUE THREAD

**Issue by Slarky** [saschaleib/dokuwiki-template-ad-hominem#58]
Hi,

I'm linking PDFs in my DokuWiki like this:

```
  * {{ ::typokurz.pdf |}}
  * Item 1
  * {{ :typokurz.pdf |}}
  * {{ :typokurz.pdf |}}
  * Item 2
```

and I noticed the list looks rather weird when using a recent ad-hominem version.

Version 1.6.4:

![ad-hominem_164](https://github.com/user-attachments/assets/77ff84df-275f-417c-abc3-457e8e61b2dc)

Version 1.6.1:

![ad-hominem_161](https://github.com/user-attachments/assets/bf552c02-3179-4595-b060-898855369977)

**Comment by saschaleib** [comment]
Hello and thanks for the notification. Indeed, this was a side-effect of a recent change that I now rather rolled back.

Since there were a couple of other changes in the dev branch anyways, I decided to make a new version which should also fix this issue (plus adds much nicer footnote symbols :-) Please update and let me know if this fixes it for you :-)

**Comment by Slarky** [comment]
Looks good now, thank you :+1:
